### ISSUE TITLE
Change Quality?

### ISSUE THREAD

**Issue by gonace** [SkylerLipthay/Spasm#1]
There is as I can see no way to change quality, is this something that can be added?

**Comment by SkylerLipthay** [comment]
Thanks for your comment!

This is not something that can be added without major modification. Right now, Spasm uses Twitch's HLS stream, which lacks quality control options. Twitch has recently rolled out HTML5 video support (which obviously has quality controls), so Spasm should probably move in that direction as well. I have suspicion that Twitch will soon entirely remove their HLS support. I have vague plans to change the protocol accordingly, but unfortunately I don't have the time right now.
